  var context={
  name: [
    "Yehuda",
    "Alan",
    "Charles",
    "Arthur",
    "Gawain",
    "Bors",
    "Perceval",
    "Pellinore",
    "Bedivere",
    "Galahad",
    "Gareth",
    "Kay",
    "Lamorak",
    "Lancelot",
    "Tristan",
    "Rowse",
    "Pellers",
    "Bagdemagus",
    "Uriens",
    "Belmont",
    "Accolon",
    "Agloval",
    "Agramore",
    "Agravin",
    "Agrawain",
    "Aliduke",
    "Arnold",
    "Gravaunt",
    "Astamor"
  ],

    title: [
    "Desaparecido",
    "Desterrado",
    "Olvidado",
    "Encantado",
    "Encantador",
    "Soberbioso",
    "Corrompido",
    "Triste",
    "Alegre",
    "Eterno",
    "Maldito",
    "Orgulloso",
    "Vanidoso",
    "Valiente",
    "Invencible",
    "Amable",
    "Astuto",
    "Imberbe",
    "Huidizo",
    "Cobarde",
    "Aparecido",
    "Grande",
    "Majestuoso",
    "Inevitable",
    "Atormentado",
    "Divino",
    "Agraciado",
    "Gallardo",
    "Iluminado",
    "Sabio",
    "Indescriptible",
    "Anciano",
    "Joven",
    "Gigante",
    "Ominoso",
    "Caprichoso",
    "Consentido",
    "Noble",
    "Erudito",
    "Ingenioso",
    "Solitario",
    "Loco",
    "Santo",
    "Putrefacto",
    "Curioso"
  ],

    place: [
    "Valle",
    "Lago",
    "Monte",
    "Islote",
    "Mar",
    "Precipicio",
    "Pueblo",
    "Castillo",
    "Fuerte",
    "Llano",
    "Monasterio",
    "Refugio",
    "Campo",
    "Pozo",
    "Río",
    "Pico",
    "Istmo",
    "Archipiélago"
  ],

    adj: [
    "Quemado",
    "Hermoso",
    "de los Cuervos",
    "Tormentoso",
    "Plácido",
    "Tranquilo",
    "Terrible",
    "Oscuro",
    "Desolado",
    "Olvidado",
    "Neblinoso",
    "Invisible",
    "Oculto",
    "de la Noche Perpetua",
    "Arrasado",
    "Solitario",
    "Pútrido",
    "Frío",
    "Sombrío",
    "Inmortal"
  ],

    story: [
    "Empeñó su vida en la búsqueda de la inmortalidad",
    "Ganó inumerables batallas sin apenas rasguño",
    "Se ganó la confianza de reyes y reinas con su valía",
    "Encontró la cura de la terrible enfermedad que asolaba al reino",
    "De pasado oscuro, dedicó el resto de su vida a enmendar sus errores",
    "Entrenó sin descanso para poder vencer a su gran rival algún día",
    "Se empeñó con valía en la protección de su señor",
    "Nunca fue diestro con la espada, lo cuál siempre trató de ocultar",
    "Luchó con valía en una cruenta guerra contra su propia familia",
    "Siempre trató de prestar su ayuda a los más débiles",
    "Fue conocido por su recto carácter y gran hontestidad",
    "Era amado profundamente por todas las gentes del pueblo",
    "Acabó con el último dragón del reino sin apenas ayuda",
    "Su inigualable ingenio le hacía la envidia de palacio",
    "Jamás se perturbó ni ante la mayor tragedia",
    "Decapitó a una bestia que aterrorizaba su tierra",
    "Destronó a un tirano que usurpaba el trono de su legítimo dueño",
    "Se contaba de él que jamás conoció la derrota",
    "Salió victorioso de más de cien batallas",
    "Querido en su tierra y estimado por sus gentes",
    "Volvió a la vida en dos ocasiones, llegando a la edad de 130 años",
    "Descubrió una ciudad que se creía de leyenda",
    "Halló un tesoro hundido y jamás reveló su paradero",
    "Alardeaba de haberse batido en duelo con el mismísimo Diablo",
    "Evitó numerosas batallas gracias a su don para la diplomacia"
  ],

    outcome: [
    "pereció en una pelea totalmente inconsecuente",
    "sucumbió a un padecimiento desconocido en medio del invierno",
    "un día desapareció sin dejar rastro",
    "fue envenenado por quien creía su más fiel amigo",
    "una noche sin luna fue acuchillado por un viejo enemigo que creía muerto",
    "se ahogó en una laguna que parecía menos profunda de lo que era",
    "cayó por un precipicio cuando intentaba recoger flores para su amada",
    "fue ajusticiado por traicionar a la corona",
    "fue exiliado a unas tierras remotas debido a un terrible malentendido",
    "una madrugada de verano emprendió un viaje en barco del que jamás volvió",
    "enloqueció y fue encerrado en una remota hermita",
    "fue asesinado por unos bandidos que querían robar su hermosa armadura",
    "un hechizo le mantuvo cautivo el resto de sus días en un castillo abandonado",
    "fue atacado por bestias feroces durante un paseo matutino",
    "sufrió lo que no puede si no describirse como ira de Dios",
    "fue empalado al caerse accidentalmente sobre su propia espada",
    "se perdió su rastro en los confines del mundo",
    "naufragó en una tierra desconocida",
    "cayó en un agujero sin fondo",
    "fue alcanzado por un relámpago el día del nacimiento de su único hijo",
    "falleció a manos de un hombre desarmado",
    "murió estando preso en una solitaria celda",
    "fue decapitado y su cabeza llevada como trofeo a una tierra lejana",
    "conoció un destino aciago al venturarse a la mar",
    "fue injustamente apresado por un crimen que no cometió",
    "conoció la muerte a manos de un ingenio mecánico",
    "fue hechizado olvidando así su identidad y antiguas gestas",
    "fue envenenado por error durante un banquete en palacio para celebrar su llegada",
    "cayó aparatosamente de su caballo hieríendose mortalmente",
    "murió a causa de una infección en una pequeña herida sin importancia",
    "murió pobre víctima de sus vicios",
    "fue endemoniado sin poder volver a sentir paz"
  ]

}